# Generated by Django 5.2 on 2025-04-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult', '0003_alter_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
